[3] Login script/[1] Script/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(null, 'Auth\LoginController@show')->name('login');
Route::post(null, 'Auth\LoginController@login')->name('login');
    
Route::group(['middleware' => 'auth'], function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['prefix' => 'settings', 'as' => 'settings.'], function() {
        Route::get(null, 'SettingsController@index')->name('index');
        Route::put('personal', 'SettingsController@update_personal')->name('personal');
        Route::put('password', 'SettingsController@update_password')->name('password');
    });

    Route::group(['prefix' => 'user', 'as' => 'user.'], function() {
        Route::get(null, 'UserController@index')->name('index');
        
        Route::get('/create', 'UserController@create')->name('create');
        Route::post('/store', 'UserController@store')->name('store');
        
        Route::get('/{id}', 'UserController@show')->name('show');
        Route::delete('/{id}', 'UserController@destroy')->name('destroy');

        Route::get('/{id}/edit', 'UserController@edit')->name('edit');

        Route::put('/{id}/update', 'UserController@update')->name('update');
        Route::put('/{id}/active/{action}', 'UserController@active')->name('active');
    });
});

[3] Login script/[1] Script/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, SerializesModels, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

[3] Login script/[1] Script/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\UpdateUserRequest;
use App\Http\Requests\StoreUserRequest;
use App\Repositories\UserRepository;
use Illuminate\Support\Facades\Mail;
use App\Mail\DeleteUser;

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

use App\User;
use Auth;
use Session;
use Hash;
use DB;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('id')->paginate(8);
        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserRequest $request)
    {
        $request = $request->except('_method', '_token', 'password_confirmation');
            
        if(array_key_exists('password', $request)) {
            $request['password'] = Hash::make($request['password']);
        }

        $id = DB::table('users')->insertGetId($request);
        $search = User::FindOrFail($id);
        $search->assignRole('user');

        Session::flash('success', trans('message.user.added'));

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(int $id)
    {
        $user = User::findOrFail($id);
        $permissions = $user->getAllPermissions();
        
        return view('user.show', compact('user', 'permissions'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(int $id)
    {
        $user = User::findOrFail($id);
        return view('user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
        $errors = new \Illuminate\Support\MessageBag();

        // Check if the user can edit another user;
        if(!Auth::User()->can('edit.user')) {
            $errors->add(null, trans('message.rights.no_required_permissions'));
        }

        // If the password is changed, check if the user has the right permission;
        else if($request->password && !Auth::User()->can('edit.password.user')) {
            $errors->add(null, trans('message.rights.no_required_permissions'));
        }

        else {
            // Take all the used requests except the default laravel ones and the password confirmation;
            $request = $request->except('_method', '_token', 'password_confirmation');
            
            // If password exits, create a new hash and override the existing password request;
            if(array_key_exists('password', $request)) {
                $request['password'] = Hash::make($request['password']);
            }

            // Update users;
            DB::table('users')->where('id', $id)->update($request);
            Session::flash('success', trans('message.settings.success'));
        }

        // Return back with errors if needed;
        return back()->withErrors($errors);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function active(int $id, bool $status)
    {
        $errors = new \Illuminate\Support\MessageBag();

        // Check if the user can edit another user;
        if(!Auth::User()->can('edit.user') || !Auth::User()->can('activate.user')) {
            $errors->add(null, trans('message.rights.no_required_permissions'));
        }

        // Its not possible to change the active-status of your own account;
        // This is for security-reasons;
        else if(Auth::Id() === $id) {
            $errors->add(null, trans('message.settings.active_own_account'));
        }
        
        // Whoo, there are no errros;
        else {            
            DB::table('users')->where('id', $id)->update(['active' => !$status]);
            Session::flash('success', trans('message.settings.success'));
        }

        // Return back with errors if needed;
        return back()->withErrors($errors);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::FindOrFail($id);
        $errors = new \Illuminate\Support\MessageBag();
        
        // Check if the user has the permission to delete the user;
        if(!Auth::User()->can('delete.user')) {
            $errors->add(null, trans('message.rights.no_required_permissions'));
        }
        
        // Check if the user is an administrator - if so THIS IS NOT POSSIBLE!;
        elseif($user->hasrole('administrator')) {            
            $errors->add(null, trans('message.user.delete_admin'));
        }

        else {
            $user->delete();

            Session::flash('success', trans('message.user.deleted'));
            return redirect()->route('user.index');
        }

        return back()->withErrors($errors);
    }
}

[3] Login script/[1] Script/resources/views/user/create.blade.php
@extends('parts.header')

@section('content')
    @can('create.user')
        <div class="row">
            <div class="col">
                @if($errors->first())
                    <div class="alert alert-icon alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert"></button>
                        <i class="fe fe-alert-triangle mr-2" aria-hidden="true"></i> {{ $errors->first() }}
                    </div>
                @endif

                @if (Session::has('success'))
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert"></button>
                        {{ Session::get('success') }}
                    </div>
                @endif
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Maak een nieuw account</h3>
                    </div>

                    <div class="card-body p-0 px-3">
                        <form action="{{ route('user.store') }}" method="post">
                            @method('post')
                            @csrf
                                
                            <div class="tab-content">
                                <div class="tab-pane px-3 pb-3 active show" id="account" role="tabpanel" aria-labelledby="account-tab">
                                    <div class="row">
                                        <div class="col-4">
                                            <legend class="pt-5 pb-3">Account</legend>
                                            
                                            <div class="form-group">
                                                <label class="control-label required">{{ trans('attribute.user.name') }}</label>
                                                <input type="text" name="name" class="form-control @if($errors->has('name')) is-invalid @endif" minlength="2" maxlength="32">
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label required">{{ trans('attribute.user.email') }}</label>
                                                <input type="email" name="email" class="form-control @if($errors->has('email')) is-invalid @endif" minlength="2" maxlength="32" autocomplete="off" required>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label required">{{ trans('attribute.user.firstname') }}</label>
                                                <input type="text" name="firstname" class="form-control @if($errors->has('firstname')) is-invalid @endif" minlength="2" maxlength="32" autocomplete="off" required>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label required">{{ trans('attribute.user.lastname') }}</label>
                                                <input type="text" name="lastname" class="form-control @if($errors->has('lastname')) is-invalid @endif" minlength="2" maxlength="32" autocomplete="off" required>
                                            </div>
                                        </div>
                                        
                                        <div class="col-4">
                                            <legend class="pt-5 pb-3">Wachtwoord</legend>

                                            <div class="form-group">
                                                <label class="form-label required">{{ trans('attribute.user.password')}}</label>
                                                <input type="password" name="password" class="form-control @if($errors->has('password')) is-invalid @endif" minlength="2" maxlength="32" autocomplete="off" required/>
                                            </div>
                
                                            <div class="form-group">
                                                <label class="form-label required">{{ trans('attribute.user.password_confirmation')}}</label>
                                                <input type="password" name="password_confirmation" class="form-control @if($errors->has('password_confirmation')) is-invalid @endif"  minlength="2" maxlength="32" autocomplete="off" required/>
                                            </div>
                                        </div>

                                        <div class="col-4">
                                            <legend class="pt-5 pb-3">Social media</legend>

                                            <div class="form-group">
                                                <label class="control-label">{{ trans('attribute.user.social_twitter') }}</label>
                                                <input type="text" name="social_twitter" class="form-control @if($errors->has('social_twitter')) is-invalid @endif" minlength="1" maxlength="32" placeholder="https://twitter.com/" autocomplete="off" required>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label">{{ trans('attribute.user.social_facebook') }}</label>
                                                <input type="text" name="social_facebook" class="form-control @if($errors->has('social_facebook')) is-invalid @endif" minlength="1" maxlength="32" autocomplete="off" required>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label">{{ trans('attribute.user.social_instagram') }}</label>
                                                <input type="text" name="social_instagram" class="form-control @if($errors->has('social_instagram')) is-invalid @endif" minlength="1" maxlength="32" autocomplete="off" required>
                                            </div>

                                            <div class="form-group">                                        
                                                <div class="alert alert-warning alert-dismissible">
                                                    <button type="button" class="close" data-dismiss="alert"></button>
                                                    Wilt u geen social media gebruiken? Gebruik dan <b>#</b>.
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="card-footer text-right">
                                        <button class="btn btn-primary" type="submit">Maak account</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @else
        <div class="alert alert-warning alert-dismissible">
            <button type="button" class="close" data-dismiss="alert"></button>
            Je hebt geen toegang tot deze pagina.
        </div>
    @endcan
@endsection

[3] Login script/[1] Script/resources/views/user/edit.blade.php
@extends('parts.header')

@section('content')
    <div class="row">
        <div class="col">
            @if($errors->first())
                <div class="alert alert-icon alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert"></button>
                    <i class="fe fe-alert-triangle mr-2" aria-hidden="true"></i> {{ $errors->first() }}
                </div>
            @endif

            @if (Session::has('success'))
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert"></button>
                    {{ Session::get('success') }}
                </div>
            @endif
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            @if(!$user->active)
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert"></button>
                    <b>Let op:</b> dit account is niet actief op dit moment.
                </div>
            @endif

            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Bewerk gebruiken</h3>

                    @if($user->id != Auth::Id())
                        <div class="card-options">
                            @can('delete.user')
                                <form action="{{ route('user.destroy', [$user->id]) }}" method="post">
                                    @method('delete')
                                    @csrf

                                    <input type="submit" class="btn btn-danger mr-2" value="Verwijderen">
                                </form>
                            @endcan
                        
                            @can('activate.user')
                            <form action="{{ route('user.active', [$user->id, $user->active]) }}" method="post">
                                @method('put')
                                @csrf
        
                                <input type="submit" class="btn @if($user->active) btn-danger @else btn-success @endif ml-2" value="@if($user->active) Deactiveer account @else Activeer account @endif">
                            </form>
                            @endcan
                        </div>
                    @endif
                </div>

                <div class="card-body p-0 px-3">
                    <form action="{{ route('user.update', [$user->id]) }}" method="post">
                        @method('put')
                        @csrf
                            
                        <div class="tab-content">
                            <div class="tab-pane px-3 pb-3 active show" id="account" role="tabpanel" aria-labelledby="account-tab">
                                <div class="row">
                                    <div class="col-4">
                                        <legend class="pt-5 pb-3">Account</legend>
                                        
                                        <div class="form-group">
                                            <label class="control-label">{{ trans('attribute.user.name') }}</label>
                                            <input type="text" class="form-control @if($errors->has('name')) is-invalid @endif" minlength="2" maxlength="32" value="{{ $user->name }}" disabled>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label required">{{ trans('attribute.user.email') }}</label>
                                            <input type="email" name="email" class="form-control @if($errors->has('email')) is-invalid @endif" minlength="2" maxlength="32" autocomplete="off" value="{{ $user->email }}" required>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label required">{{ trans('attribute.user.firstname') }}</label>
                                            <input type="text" name="firstname" class="form-control @if($errors->has('firstname')) is-invalid @endif" minlength="2" maxlength="32" autocomplete="off" value="{{ $user->firstname }}" required>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label required">{{ trans('attribute.user.lastname') }}</label>
                                            <input type="text" name="lastname" class="form-control @if($errors->has('lastname')) is-invalid @endif" minlength="2" maxlength="32" autocomplete="off" value="{{ $user->lastname }}" required>
                                        </div>
                                    </div>
                                    
                                    <div class="col-4">
                                        <legend class="pt-5 pb-3">Wachtwoord</legend>

                                        <div class="form-group">
                                            <label class="form-label">{{ trans('attribute.user.password')}}</label>
                                            <input type="password" name="password" class="form-control @if($errors->has('password')) is-invalid @endif" minlength="2" maxlength="32" autocomplete="off"/>
                                        </div>
            
                                        <div class="form-group">
                                            <label class="form-label">{{ trans('attribute.user.password_confirmation')}}</label>
                                            <input type="password" name="password_confirmation" class="form-control @if($errors->has('password_confirmation')) is-invalid @endif"  minlength="2" maxlength="32" autocomplete="off"/>
                                        </div>
                                    </div>

                                    <div class="col-4">
                                        <legend class="pt-5 pb-3">Social media</legend>
                                                    
                                        <div class="form-group">
                                            <label class="control-label">{{ trans('attribute.user.social_twitter') }}</label>
                                            <input type="text" name="social_twitter" class="form-control @if($errors->has('social_twitter')) is-invalid @endif" minlength="1" maxlength="32" placeholder="https://twitter.com/" value="{{ $user->social_twitter }}" autocomplete="off">
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label">{{ trans('attribute.user.social_facebook') }}</label>
                                            <input type="text" name="social_facebook" class="form-control @if($errors->has('social_facebook')) is-invalid @endif" minlength="1" maxlength="32" placeholder="https://facebook.com" value="{{ $user->social_facebook }}" autocomplete="off">
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label">{{ trans('attribute.user.social_instagram') }}</label>
                                            <input type="text" name="social_instagram" class="form-control @if($errors->has('social_instagram')) is-invalid @endif" minlength="1" maxlength="32" placeholder="https://instagram.com" value="{{ $user->social_instagram }}" autocomplete="off">
                                        </div>
                                    </div>
                                </div>

                                <div class="card-footer text-right">
                                    <button class="btn btn-primary" type="submit">Update account</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

[3] Login script/[1] Script/resources/views/user/index.blade.php
@extends('parts.header')

@section('content')
    <div class="row">
        <div class="col">
            @if($errors->first())
                <div class="alert alert-icon alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert"></button>
                    <i class="fe fe-alert-triangle mr-2" aria-hidden="true"></i> {{ $errors->first() }}
                </div>
            @endif

            @if (Session::has('success'))
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert"></button>
                    {{ Session::get('success') }}
                </div>
            @endif
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Overzicht gebruikers ({{ $users->total() }})</h3>

                    @can('create.user')
                        <div class="card-options">
                            <a href="{{ route('user.create') }}" class="btn btn-secondary"><i class="fe fe-plus-circle"></i> Maak een account</a>
                        </div>
                    @endcan
                </div>

                <div class="table-responsive">
                    <table class="table table-hover table-outline table-vcenter text-nowrap card-table" width="100%">
                        <thead>
                            <tr>
                                <th class="text-center w-1"></th>
                                <th>{{ trans('attribute.user.name') }}</th>
                                <th>{{ trans('attribute.user.email') }}</th>
                                <th >{{ trans('attribute.user.rank') }}</th>
                                <th class="text-center" width="60"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td class="text-center">
                                         <span class="avatar @if($user->active) avatar-green @else avatar-red @endif">
                                            {{ mb_substr($user->firstname, 0, 1, "UTF-8") .  mb_substr($user->lastname, 0, 1, "UTF-8") }}
                                        </span>
                                    </td>
                                    
                                    <td>
                                        <div>{{ $user->name }}</div>
                                        <div class="small text-muted">
                                            {{ $user->firstname }} {{ $user->lastname }}
                                        </div>
                                    </td>

                                    <td>
                                        {{ $user->email }}
                                    </td>
                                    
                                    <td>
                                        {{ ucfirst( isset($user->roles[0]) ? $user->roles[0]->name : 'User') }}
                                    </td>
                                    
                                    <td>                                      
                                        @can('edit.user')
                                            <a href="{{ route('user.edit', $user->id) }}" class="btn btn-secondary"><i class="fe fe-edit-2" data-toggle="tooltip" data-original-title="Bewerk profiel"></i></a>
                                        @endcan

                                        <a href="{{ route('user.show', $user->id) }}" class="btn btn-primary"><i class="fe fe-user" data-toggle="tooltip" data-original-title="Bekijk gebruiker"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

                <div class="modal-footer">
                    {{ $users->links() }}
                </div>
            </div>
        </div>
    </div>

@endsection